package sk.upjs.ics.tennismanager;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class UzivatelMainForm extends javax.swing.JFrame {
    
    HracTableModel hracTableModel = new HracTableModel();
    HracDao hracDao = DaoFactory.INSTANCE.getHracDao();
    
    TurnajTableModel turnajTableModel = new TurnajTableModel();
    TurnajDao turnajDao = DaoFactory.INSTANCE.getTurnajDao();
    
    public UzivatelMainForm() {
        initComponents();
        refreshHraci();
        refreshTurnaje();
        
        zarovnajCislaVTabulkach();
        
        vsJlabel.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        this.naplnComboBox();
        AutoCompleteDecorator.decorate(this.hrac1ComboBox);
        AutoCompleteDecorator.decorate(this.hrac2ComboBox);
        this.getContentPane().setBackground(Color.decode("#D7FFB8"));
        addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                UzivatelMainForm.this.dispose();
                new LoginForm().setVisible(true);
            }
            
        });
    }
    
    public void naplnComboBox() {
        for (Hrac h : hracDao.dajVsetky()) {
            hrac1ComboBox.addItem(h);
            hrac2ComboBox.addItem(h);
        }
        hrac1ComboBox.setSelectedItem(null);
        hrac2ComboBox.setSelectedItem(null);
    }
    
    private void refreshHraci() {
        hracTableModel.refresh();
    }
    
    private void refreshTurnaje() {
        turnajTableModel.refresh();
    }
    
    private void zarovnajCislaVTabulkach() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        hracTable.setDefaultRenderer(Integer.class, centerRenderer);
        hracTable.setDefaultRenderer(Double.class, centerRenderer);
        
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);
        turnajTable.setDefaultRenderer(Integer.class, leftRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        hraciTab = new javax.swing.JScrollPane();
        hracTable = new javax.swing.JTable();
        trunajeTab = new javax.swing.JScrollPane();
        turnajTable = new javax.swing.JTable();
        stavkovyPoradcaTab = new javax.swing.JPanel();
        hrac1ComboBox = new javax.swing.JComboBox();
        hrac2ComboBox = new javax.swing.JComboBox();
        vsJlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hracTable.setModel(hracTableModel);
        hraciTab.setViewportView(hracTable);

        jTabbedPane1.addTab("Hráči", hraciTab);

        turnajTable.setModel(turnajTableModel);
        trunajeTab.setViewportView(turnajTable);

        jTabbedPane1.addTab("Turnaje", trunajeTab);

        hrac1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        vsJlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vsJlabel.setText("VS");

        javax.swing.GroupLayout stavkovyPoradcaTabLayout = new javax.swing.GroupLayout(stavkovyPoradcaTab);
        stavkovyPoradcaTab.setLayout(stavkovyPoradcaTabLayout);
        stavkovyPoradcaTabLayout.setHorizontalGroup(
            stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stavkovyPoradcaTabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(hrac1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(vsJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrac2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        stavkovyPoradcaTabLayout.setVerticalGroup(
            stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stavkovyPoradcaTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrac1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrac2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", stavkovyPoradcaTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UzivatelMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox hrac1ComboBox;
    private javax.swing.JComboBox hrac2ComboBox;
    private javax.swing.JTable hracTable;
    private javax.swing.JScrollPane hraciTab;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel stavkovyPoradcaTab;
    private javax.swing.JScrollPane trunajeTab;
    private javax.swing.JTable turnajTable;
    private javax.swing.JLabel vsJlabel;
    // End of variables declaration//GEN-END:variables
}
