package sk.upjs.ics.tennismanager;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class UzivatelMainForm extends javax.swing.JFrame {

    HracTableModel hracTableModel = new HracTableModel();
    HracDao hracDao = DaoFactory.INSTANCE.getHracDao();

    TurnajTableModel turnajTableModel = new TurnajTableModel();
    TurnajDao turnajDao = DaoFactory.INSTANCE.getTurnajDao();

    public UzivatelMainForm() {
        initComponents();
        refreshHraci();
        refreshTurnaje();

        zarovnajCislaVTabulkach();

        vsJlabel.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        this.naplnComboBox();
        AutoCompleteDecorator.decorate(this.hrac1ComboBox);
        AutoCompleteDecorator.decorate(this.hrac2ComboBox);
        this.getContentPane().setBackground(Color.decode("#D7FFB8"));
        hraciTab.setBackground(Color.decode("#D7FFB8"));
        turnajTab.setBackground(Color.decode("#D7FFB8"));
        stavkovyPoradcaTab.setBackground(Color.decode("#D7FFB8"));

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((dim.width - this.getSize().width) / 2, (dim.height - this.getSize().height) / 2);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                UzivatelMainForm.this.dispose();
                new LoginForm().setVisible(true);
            }

        });
    }

    public void naplnComboBox() {
        for (Hrac h : hracDao.dajVsetky()) {
            hrac1ComboBox.addItem(h);
            hrac2ComboBox.addItem(h);
        }
        hrac1ComboBox.setSelectedItem(null);
        hrac2ComboBox.setSelectedItem(null);
    }

    private void refreshHraci() {
        hracTableModel.refresh();
    }

    private void refreshTurnaje() {
        turnajTableModel.refresh();
    }

    private void zarovnajCislaVTabulkach() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        hracTable.setDefaultRenderer(Integer.class, centerRenderer);
        hracTable.setDefaultRenderer(Double.class, centerRenderer);

        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);
        turnajTable.setDefaultRenderer(Integer.class, leftRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        hraciTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hracTable = new javax.swing.JTable();
        turnajTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        turnajTable = new javax.swing.JTable();
        stavkovyPoradcaTab = new javax.swing.JPanel();
        hrac1ComboBox = new javax.swing.JComboBox();
        hrac2ComboBox = new javax.swing.JComboBox();
        vsJlabel = new javax.swing.JLabel();
        vyhodnotButton = new javax.swing.JButton();
        vysledokLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hracTable.setModel(hracTableModel);
        hracTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hracTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hracTable);

        javax.swing.GroupLayout hraciTabLayout = new javax.swing.GroupLayout(hraciTab);
        hraciTab.setLayout(hraciTabLayout);
        hraciTabLayout.setHorizontalGroup(
            hraciTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hraciTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        hraciTabLayout.setVerticalGroup(
            hraciTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hraciTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hráči", hraciTab);

        turnajTable.setModel(turnajTableModel);
        turnajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turnajTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(turnajTable);

        javax.swing.GroupLayout turnajTabLayout = new javax.swing.GroupLayout(turnajTab);
        turnajTab.setLayout(turnajTabLayout);
        turnajTabLayout.setHorizontalGroup(
            turnajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turnajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        turnajTabLayout.setVerticalGroup(
            turnajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turnajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Turnaje", turnajTab);

        vsJlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vsJlabel.setText("VS");

        vyhodnotButton.setText("Vyhodnoť");
        vyhodnotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyhodnotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stavkovyPoradcaTabLayout = new javax.swing.GroupLayout(stavkovyPoradcaTab);
        stavkovyPoradcaTab.setLayout(stavkovyPoradcaTabLayout);
        stavkovyPoradcaTabLayout.setHorizontalGroup(
            stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stavkovyPoradcaTabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(hrac1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(vsJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(hrac2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stavkovyPoradcaTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stavkovyPoradcaTabLayout.createSequentialGroup()
                        .addComponent(vyhodnotButton)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stavkovyPoradcaTabLayout.createSequentialGroup()
                        .addComponent(vysledokLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        stavkovyPoradcaTabLayout.setVerticalGroup(
            stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stavkovyPoradcaTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(stavkovyPoradcaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrac1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrac2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vyhodnotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vysledokLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stávkový poradca", stavkovyPoradcaTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hracTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hracTableMouseClicked
        if (evt.getClickCount() == 2) {
            int vybranyRiadok = hracTable.getSelectedRow();
            Hrac hrac = hracTableModel.dajPodlaCislaRiadku(vybranyRiadok);

            HracDetailForm hracDetailForm = new HracDetailForm(this, true, hrac);
            hracDetailForm.setVisible(true);
        }
    }//GEN-LAST:event_hracTableMouseClicked

    private void turnajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnajTableMouseClicked
        if (evt.getClickCount() == 2) {
            int vybranyRiadok = turnajTable.getSelectedRow();
            Turnaj turnaj = turnajTableModel.dajPodlaCislaRiadku(vybranyRiadok);

            TurnajDetailForm turnajDetailForm = new TurnajDetailForm(this, true, turnaj);
            turnajDetailForm.setVisible(true);
        }
    }//GEN-LAST:event_turnajTableMouseClicked

    private void vyhodnotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyhodnotButtonActionPerformed
        Hrac h1 = (Hrac) hrac1ComboBox.getSelectedItem();
        Hrac h2 = (Hrac) hrac2ComboBox.getSelectedItem();
        vysledokLabel.setHorizontalAlignment((int) CENTER_ALIGNMENT);

        if (h1.getKondicia() > h2.getKondicia()) {
            vysledokLabel.setText(h1.getMeno() + " " + h1.getPriezvisko());
            return;
        } else if (h1.getKondicia() < h2.getKondicia()) {
            vysledokLabel.setText(h2.getMeno() + " " + h2.getPriezvisko());
            return;
        }
        // tu si dam zoznam poslednych piatich zapasov oboch a uvidim ako sa vyvija ich kondicia
        //podla toho rozhodnem
    }//GEN-LAST:event_vyhodnotButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UzivatelMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UzivatelMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox hrac1ComboBox;
    private javax.swing.JComboBox hrac2ComboBox;
    private javax.swing.JTable hracTable;
    private javax.swing.JPanel hraciTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel stavkovyPoradcaTab;
    private javax.swing.JPanel turnajTab;
    private javax.swing.JTable turnajTable;
    private javax.swing.JLabel vsJlabel;
    private javax.swing.JButton vyhodnotButton;
    private javax.swing.JLabel vysledokLabel;
    // End of variables declaration//GEN-END:variables
}
